# docker-compose.yml
version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

volumes:
  grafana_data:
