# docker-compose.yml
version: "3.8"
services:
  db:
    image: mongo:latest
    container_name: mongodb_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
